#!/usr/bin/env bash
# Pings 5 times specified IP passed as first cmd line argument 
if [ $# -eq 0 ]
    then
        echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
        exit 1
fi
ping "$1" -c 5